[build]
  # The command to build your site.
  command = "python build.py"
  # The directory to publish.
  publish = "build"

[build.environment]
  # Specify the Python version.
  PYTHON_VERSION = "3.11"